### ISSUE TITLE
Tag named HEAD makes it impossible to pull

### ISSUE THREAD

**Issue by jasonganub** [integrii/go-redis-migrator#4]
Hi Eric,

I noticed that there's a tag named HEAD which causes an issue when pulling code.

So I'm not able to pull code unless I wipe out the entire repo each time. Also, all forks will fail.

<img width="305" alt="Screen Shot 2021-07-05 at 10 24 27" src="https://user-images.githubusercontent.com/5640407/124409591-2ec04300-dd7b-11eb-86b0-87d59a6be402.png">

Reference:
https://stackoverflow.com/questions/1692892/warning-refname-head-is-ambiguous
The 3rd answer fixed my problem which is to delete the tag.

Can you please delete the tag named HEAD?
```git tag -d HEAD```

**Comment by jasonganub** [comment]
cc: @integrii

**Comment by integrii** [comment]
Deleted!  Sorry about that.
